language: java

os: linux

env:
  global:
    - SPARK_MASTER=local[2]
    - HADOOP_URL=file:///

sudo: required

jdk:
  - oraclejdk9

script: mvn clean install -DskipTests cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)